/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.toedter.calendar.JDateChooser;
import dao.CabekaDAO;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import model.Cabeka;

/**
 *
 * @author Serge
 */
public class CabekaView extends javax.swing.JFrame implements DataCallback {
    CabekaDAO dao = new CabekaDAO();
    Cabeka cabeka;
    String[] data;
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    private ArrayList<JTextField> textFields = new ArrayList<>();;
    private ArrayList<JTextArea> textAreas = new ArrayList<>();;
    private ArrayList<JDateChooser> dateChoosers = new ArrayList<>();;
    /**
     * Creates new form CabekaView
     */
    public CabekaView() {
        initComponents();
        textFields.add(inputInduk);
        textFields.add(inputPengampu);
        textFields.add(tfNamaSiswa);
        textFields.add(tfNamaPengampu);
        textAreas.add(inputPermasalahan);
        textAreas.add(inputSolusi);
        dateChoosers.add(inputTgl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        header_text = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inputInduk = new javax.swing.JTextField();
        btnLookupSiswa = new javax.swing.JButton();
        tfNamaSiswa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputTgl = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputPermasalahan = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputSolusi = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbKehadiran = new javax.swing.JComboBox<>();
        scrCabeka = new javax.swing.JScrollPane();
        tableCabeka = new javax.swing.JTable();
        interectPanel1 = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        tfNamaPengampu = new javax.swing.JTextField();
        btnLookupPengampu = new javax.swing.JButton();
        inputPengampu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        header.setBackground(new java.awt.Color(0, 0, 153));

        header_text.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        header_text.setForeground(new java.awt.Color(255, 255, 255));
        header_text.setText("CABEKA");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(header_text)
                .addContainerGap(918, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header_text, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nomor Induk");

        inputInduk.setOpaque(true);
        inputInduk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputIndukKeyReleased(evt);
            }
        });

        btnLookupSiswa.setText("Lookup");
        btnLookupSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLookupSiswaActionPerformed(evt);
            }
        });

        tfNamaSiswa.setEditable(false);
        tfNamaSiswa.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tanggal");

        inputTgl.setDateFormatString("dd-MM-yyyy");
        inputTgl.setMaxSelectableDate(new java.util.Date(253370743302000L));
        inputTgl.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                inputTglPropertyChange(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Permasalahan");

        inputPermasalahan.setColumns(20);
        inputPermasalahan.setRows(5);
        jScrollPane1.setViewportView(inputPermasalahan);

        inputSolusi.setColumns(20);
        inputSolusi.setRows(5);
        jScrollPane2.setViewportView(inputSolusi);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Solusi");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Kehadiran");

        cbKehadiran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sakit", "Izin", "Alpha" }));

        tableCabeka.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCabeka.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableCabekaMousePressed(evt);
            }
        });
        scrCabeka.setViewportView(tableCabeka);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCancel.setText("Clear");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSaveMousePressed(evt);
            }
        });

        javax.swing.GroupLayout interectPanel1Layout = new javax.swing.GroupLayout(interectPanel1);
        interectPanel1.setLayout(interectPanel1Layout);
        interectPanel1Layout.setHorizontalGroup(
            interectPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(interectPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        interectPanel1Layout.setVerticalGroup(
            interectPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(interectPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(interectPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrCabeka)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbKehadiran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(interectPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbKehadiran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(interectPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrCabeka, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tfNamaPengampu.setEditable(false);
        tfNamaPengampu.setEnabled(false);

        btnLookupPengampu.setText("Lookup");
        btnLookupPengampu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLookupPengampuActionPerformed(evt);
            }
        });

        inputPengampu.setOpaque(true);
        inputPengampu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputPengampuKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Guru Pengampu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(inputInduk, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLookupSiswa)
                                .addGap(12, 12, 12)
                                .addComponent(tfNamaSiswa))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(inputTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(inputPengampu, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLookupPengampu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfNamaPengampu)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputInduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLookupSiswa)
                    .addComponent(tfNamaSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputPengampu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLookupPengampu)
                    .addComponent(tfNamaPengampu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputIndukKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputIndukKeyReleased
//        tfNamaSiswa.setText(dao.getNamaSiswa(inputInduk.getText()));
        loadData();
    }//GEN-LAST:event_inputIndukKeyReleased

    private void btnLookupSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLookupSiswaActionPerformed
        LookView look = new LookView(this, true, "Data Siswa", dao.getLookSiswa());
        look.setVisible(true);
        inputInduk.setText(data[0]);
        tfNamaSiswa.setText(data[1]);
    }//GEN-LAST:event_btnLookupSiswaActionPerformed

    private void btnLookupPengampuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLookupPengampuActionPerformed
        LookView look = new LookView(this, true, "Data Guru", dao.getLookGuru());
        look.setVisible(true);
        inputPengampu.setText(data[0]);
        tfNamaPengampu.setText(data[1]);
    }//GEN-LAST:event_btnLookupPengampuActionPerformed

    private void inputPengampuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputPengampuKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPengampuKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loadData();
        inputTgl.setMaxSelectableDate(new Date(System.currentTimeMillis()));
    }//GEN-LAST:event_formWindowOpened

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        loadData();
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (confirm("Data akan dihapus", "Hapus Data") == JOptionPane.NO_OPTION) return;

        dao.deleteCabeka(inputInduk.getText(), new Date(inputTgl.getDate().getTime()));
        loadData();
        removeInput();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if (confirm("Input akan dihapus", "Hapus Input") == JOptionPane.NO_OPTION) return;

        removeInput();
        loadData();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMousePressed
        if (checkFill() == false) {
            JOptionPane.showMessageDialog(this, "Anda belum menginput semuanya");
            return;
        }
        
        if (confirm("Data akan disimpan", "Simpan Data") == JOptionPane.NO_OPTION) return;

        cabeka = new Cabeka();
        cabeka.setNis(inputInduk.getText());
        cabeka.setTgl(new Date(inputTgl.getDate().getTime()));
        cabeka.setNik(inputPengampu.getText());
        cabeka.setPermasalahan(inputPermasalahan.getText());
        cabeka.setSolusi(inputSolusi.getText());
        String kehadiran = "";
        switch (cbKehadiran.getSelectedItem().toString()) {
            case "Sakit":
                kehadiran = "S";
                break;
            case "Izin":
                kehadiran = "I";
                break;
            case "Alpha":
                kehadiran = "A";
                break;
        }
        cabeka.setKehadiran(kehadiran);
        
        dao.saveCabeka(cabeka);
        
        removeInput();
        loadData();
    }//GEN-LAST:event_btnSaveMousePressed

    private void tableCabekaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCabekaMousePressed
        int SelectedRow = tableCabeka.rowAtPoint(evt.getPoint());
        
        if (SelectedRow != -1) {
            String nis = tableCabeka.getValueAt(SelectedRow, 0).toString();
            String tgl = sdf.format(tableCabeka.getValueAt(SelectedRow, 2));
            loadInput(nis, Date.valueOf(tgl));
        }
    }//GEN-LAST:event_tableCabekaMousePressed

    private void inputTglPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_inputTglPropertyChange
        loadData();
    }//GEN-LAST:event_inputTglPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CabekaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CabekaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CabekaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CabekaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CabekaView view = new CabekaView();
                view.setVisible(true);
            }
        });
    }
    
    @Override
    public void onDataReceived(String[] data) {
        this.data = data;
    }
    
    private void loadData() {
        Date tgl = null;
        if (inputTgl.getDate() == null) {
            tgl = null;
        } else {
            tgl = new Date(inputTgl.getDate().getTime());
        }
        try {
            tableCabeka.setModel(dao.getModelCabeka(inputInduk.getText(), tgl));
        }
        catch (NullPointerException e) {
            tableCabeka.setModel(dao.getModelCabeka("", new Date(0)));
        }
        scrCabeka.setViewportView(tableCabeka);
    }
    
    private void loadInput(String nis, Date tgl) {
        cabeka = dao.getCabeka(nis, tgl);
        
        inputInduk.setText(cabeka.getNis());
        inputPengampu.setText(cabeka.getNik());
        inputTgl.setDate(cabeka.getTgl());
        inputPermasalahan.setText(cabeka.getPermasalahan());
        inputSolusi.setText(cabeka.getSolusi());
        
        cbKehadiran.setSelectedItem(cabeka.getKehadiran());
        
        tfNamaSiswa.setText(cabeka.getSiswa().getNama());
        tfNamaPengampu.setText(cabeka.getGuru().getNama());
    }
    
    private void removeInput() {
        for (JTextField a : textFields) {
            a.setText("");
        }
        for (JTextArea a : textAreas) {
            a.setText("");
        }
        for (JDateChooser a : dateChoosers) {
            a.setDate(null);
        }
        cbKehadiran.setSelectedIndex(0);
    }
    
    private boolean checkFill() {
        for (JTextField a : textFields) {
            if (a.getText().isEmpty()) return false;
        }
        for (JTextArea a : textAreas) {
            if (a.getText().isEmpty()) return false;
        }
        for (JDateChooser a : dateChoosers) {
            if (a.getDate() == null) return false;
        }
        if (cbKehadiran.getSelectedItem() == null) return false;
        return true;
    }
    
    public int confirm(String text, String title) {
        return JOptionPane.showOptionDialog(null, text, title, JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLookupPengampu;
    private javax.swing.JButton btnLookupSiswa;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbKehadiran;
    private javax.swing.JPanel header;
    private javax.swing.JLabel header_text;
    public static javax.swing.JTextField inputInduk;
    public static javax.swing.JTextField inputPengampu;
    private javax.swing.JTextArea inputPermasalahan;
    private javax.swing.JTextArea inputSolusi;
    private com.toedter.calendar.JDateChooser inputTgl;
    private javax.swing.JPanel interectPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane scrCabeka;
    private javax.swing.JTable tableCabeka;
    public static javax.swing.JTextField tfNamaPengampu;
    public static javax.swing.JTextField tfNamaSiswa;
    // End of variables declaration//GEN-END:variables
}
